### ISSUE TITLE
python binding missing constant

### ISSUE THREAD

**Issue by anaselli** [libyui/libyui-bindings#22]
> > > import yui
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib64/python3.5/site-packages/yui.py", line 4987, in <module>
> > >     class YOptionalWidgetFactory(_object):
> > >   File "/usr/lib64/python3.5/site-packages/yui.py", line 5003, in
> > > YOptionalWidgetFactory
> > >     def createWizard(self, parent, backButtonLabel, abortButtonLabel,
> > > nextButtonLabel, wizardMode=YWizardMode_Standard):
> > > NameError: name 'YWizardMode_Standard' is not defined

This problem is either using pyhon2 or python3. Maybe it's related to swig version (3.0.7).

**Comment by anaselli** [comment]
proposal patch is in https://gist.github.com/anaselli/791d2a67bf5721fcb86b
I have too many pending pull requests...

**Comment by anaselli** [comment]
This should have been merged
