### ISSUE TITLE
SIGABRT when accessing keySymbol on a YKeyEvent.

### ISSUE THREAD

**Issue by mpserafim** [libyui/libyui-bindings#39]
Hello,

I'm trying to acces the method "keySymbol()" on a YKeyEvent generated on a SelectionBox but I getting a SIGABRT.
For this I'm using Perl (5.32.0), libyui-bindings (2.1.1), libyui-ncurses (4.0.0), libyui (4.0.0) and swig (4.0.2).

I prepared the SelecionBox with setNotify(1) and setSendKeyEvents(1), later when I got  the event object I blessed it to a KeyEvent and tried to access the keySymbol() method.

The backtrace on gdb give me:

```
Program received signal SIGABRT, Aborted.
0x00007ffff79d4277 in raise () from /lib/libc.so.6

#0  0x00007ffff79d4277 in raise () from /lib/libc.so.6
No symbol table info available.
#1  0x00007ffff79c34af in abort () from /lib/libc.so.6
No symbol table info available.
#2  0x00007ffff6354643 in __gnu_cxx::__verbose_terminate_handler ()
    at ../../../../gcc-9.2.0/libstdc++-v3/libsupc++/vterminate.cc:95
        terminating = true
        t = <optimized out>
#3  0x00007ffff6360066 in __cxxabiv1::__terminate (handler=<optimized out>)
    at ../../../../gcc-9.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:47
No locals.
#4  0x00007ffff63600b1 in std::terminate ()
    at ../../../../gcc-9.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:57
No locals.
#5  0x00007ffff63602e4 in __cxxabiv1::__cxa_throw (obj=<optimized out>, 
    tinfo=0x7ffff6483f80 <typeinfo for std::bad_alloc>, 
    dest=0x7ffff635e7f0 <std::bad_alloc::~bad_alloc()>)
    at ../../../../gcc-9.2.0/libstdc++-v3/libsupc++/eh_throw.cc:95
        globals = <optimized out>
        header = 0x1575be0
#6  0x00007ffff63542de in operator new (sz=3400833647865114675)
    at /usr/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/exception.h:63
        handler = <optimized out>
        p = <optimized out>
#7  0x00007ffff63f508f in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=0x7fffffffe8b8, 
    __beg=0x2a1 <error: Cannot access memory at address 0x2a1>, __end=<optimized out>)
    at /usr/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:363
        __dnew = 3400833647865114674
#8  0x00007ffff65c12ed in YKeyEvent::keySymbol[abi:cxx11]() const (this=<optimized out>)
    at /usr/include/yui/YEvent.h:224
No locals.
#9  _wrap_YKeyEvent_keySymbol (cv=<optimized out>)
    at /usr/src/libyui-bindings-2.1.1/build/swig/perl/yui_perl.cxx:31028
        argp1 = 0x15356b8
        argvi = 0
        arg1 = <optimized out>
        res1 = <optimized out>
        result = {static npos = 18446744073709551615, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffe8a8 ""}, _M_string_length = 0, {
            _M_local_buf = "\000\000\000\000\000\000\000\000\v\000\000\000\000\000\000", 
            _M_allocated_capacity = 0}}
        sp = <optimized out>
        ax = <optimized out>
        mark = <optimized out>
        items = <optimized out>
#10 0x00007ffff7da5731 in Perl_pp_entersub () from /usr/lib/perl5/5.32.0/x86_64-linux/CORE/libperl.so
#11 0x00007ffff7d9dabd in Perl_runops_standard ()
   from /usr/lib/perl5/5.32.0/x86_64-linux/CORE/libperl.so
No symbol table info available.
#12 0x00007ffff7d34ba8 in perl_run () from /usr/lib/perl5/5.32.0/x86_64-linux/CORE/libperl.so
No symbol table info available.
#13 0x0000000000401195 in main ()
```

As far as I can see, the NCSelecionBox is generating the correct event and the NCtoY2Event is propagating but somewhere after this the objects inside the KeyEvent (keySymbol and the focusWidget) are getting invalidated.

Can someone point me where in the code I could take a look to figure this out?

Thanks in advance.

**Comment by mpserafim** [comment]
Nevermind. Perl blessing was messing things up.
I made a wrapper to cast the objects.

See ya.
